import axios from "axios";
import { TbMessageChatbot } from "react-icons/tb";
import {useState} from "react";
const Chatbot = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [imageLoading, setImageLoading] = useState(false); // For image loading
  const api_key = import.meta.env.VITE_AI_API_KEY;
  const [generatedImage, setGeneratedImage] = useState(""); // For storing image URL

  // Function to toggle chat window visibility
  const toggleChat = () => setIsOpen((prev) => !prev);

  // Function to send a message to OpenAI API

  const sendMessage = async () => {
  if (input.trim()) {
    setLoading(true);
    const newMessages = [...messages, { text: input, sender: "user" }];
    setMessages(newMessages);
    setInput("");
    // If the user is asking for an image
    if (input.toLowerCase().includes("generate image")) {
      generateImage(input); // Call image generation if the prompt contains "generate image"
    } else {
      // API call to OpenAI chat model for regular chat
      try {
        const response = await axios.post(
          "https://api.openai.com/v1/chat/completions",
          {
            model: "gpt-4.1-mini",
            messages: newMessages.map((msg) => ({
              role: msg.sender === "user" ? "user" : "assistant", // Fix: "ai" -> "assistant"
              content: msg.text,
            })),
          },
          {
            headers: {
              Authorization: `Bearer ${api_key}`,
            },
          }
        );
        const aiMessage = {
          text: response.data.choices[0].message.content,
          sender: "assistant", // Set role to 'assistant'
        };
        setMessages([...newMessages, aiMessage]);
      } catch (error) {
        console.error("Error sending message", error);
      } finally {
        setLoading(false);
      }
    }
  }
};

  // Function to generate an image using OpenAI API
  const generateImage = async (prompt) => {
    setImageLoading(true); // Set loading state for image
    try {
      const response = await axios.post(
        "https://api.openai.com/v1/images/generations",
        {
          model: "dall-e-3",
          prompt: prompt,
          n: 1,
          size: "1024x1024",
        },
        {
          headers: {
            Authorization: `Bearer ${api_key}`,
            "Content-Type": "application/json",
          },
        }
      );

      const imageUrl = response.data.data[0].url; // Get the URL of the generated image
      const imageMessage = {
        text: "Here is the image you requested:",
        sender: "ai",
        image: imageUrl,
      };
      setGeneratedImage(imageUrl); // Store image URL
      setMessages([...messages, { text: "Generating image...", sender: "ai" }, imageMessage]);
    } catch (error) {
      console.error("Error generating image:", error);
      setMessages([
        ...messages,
        { text: "Sorry, there was an error generating the image.", sender: "ai" },
      ]);
    } finally {
      setImageLoading(false); // Reset loading state
    }
  };

  return (
    <div>
      {/* Chat Button */}
      <button
        onClick={toggleChat}
        className="fixed bottom-12 right-15 bg-[#309255] text-white p-2 rounded-full shadow-xl hover:bg-[#309255] transition duration-300"
      >
        <TbMessageChatbot className="text-4xl"/> 
      </button>

      {/* Chat Window */}
      {isOpen && (
        <div className="fixed bottom-12 right-15 w-96 bg-white shadow-xl rounded-lg p-4 border border-gray-300 z-1000">
          <div className="flex justify-between items-center mb-4">
            <h2 className="font-bold text-xl">Chat with AI</h2>
            <button
              onClick={toggleChat}
              className="text-gray-500 hover:text-gray-800"
            >
              X
            </button>
          </div>
          <div className="max-h-90 overflow-y-scroll mb-4">
            {messages.map((msg, index) => (
              <div
                key={index}
                className={`mb-2 ${msg.sender === "user" ? "text-right" : ""}`}
              >
                <div
                  className={`inline-block px-4 py-2 rounded-lg max-w-xs ${
                    msg.sender === "user"
                      ? "bg-[#309255] text-white"
                      : "bg-gray-100 text-black"
                  }`}
                >
                  {msg.text}
                </div>
                {msg.image && (
                  <img
                    src={msg.image}
                    alt="Generated by AI"
                    className="mt-2 rounded-lg"
                    style={{ maxWidth: "100%", height: "auto" }}
                  />
                )}
              </div>
            ))}
            {loading && <div className="text-center text-gray-500">AI is typing...</div>}
            {imageLoading && (
              <div className="text-center text-gray-500">Generating image...</div>
            )}
          </div>
          <div className="flex items-center space-x-2">
            <input
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Type a message..."
              className="flex-1 p-2 border rounded-lg border-[#eefbf3] outline-none"
            />
            <button
              onClick={sendMessage}
              className="bg-[#309255] text-white p-2 rounded-lg outline-none"
            >
              Send
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default Chatbot;
